spring:
  profiles:
    active:
      - dog
      - EN
      - dev

logging:
  level:
    '[guru.springframework]': debug

guru:
  username: superuserYAML
  password: dbPasswordYAML
  jdbcurl: someURLforDBYAML

---

spring:
  profiles: prod

guru:
  username: ProdUsername
  password: ProdPassword
  jdbcurl: ProdURL
